spring.application.name=SuperpositionGameBackend
logging.level.org.springframework.messaging=TRACE
logging.level.org.springframework.web.socket=TRACE

jwt.key=${JWT_KEY}
jwt.expiration=${JWT_EXPIRATION}
